spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
